FROM grafana/grafana:latest

COPY datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY dashboards /etc/grafana/dashboards
